make brightness control via hotkeys exponential
openSUSE/openSUSEway pull request #113
Opened 2023-05-03 12:18 UTC by nova-r

fixes #112 
As brightness is perceived exponentially, it is more intuitive to make the brightness change exponentially as well.

2023-05-22 09:58 UTC, denisok requested changes
Otherwise doesn't work for me:
```
May 22 11:52:37 stdlen sway[4702]: Execution of -e aborted due to compilation errors.
May 22 11:52:37 stdlen sway[4702]: syntax error at -e line 1, near "%.0"
May 22 11:52:37 stdlen sway[4702]:         (Missing operator before f?)
May 22 11:52:37 stdlen sway[4702]: Bareword found where operator expected at -e line 1, near "0f"
May 22 11:52:37 stdlen sway[4702]:         (Missing operator before 0?)
May 22 11:52:37 stdlen sway[4702]: Number found where operator expected at -e line 1, near "%.0"
```

2023-05-22 09:58 UTC, denisok commented on .config/sway/config.d/50-openSUSE.conf
> +bindsym XF86MonBrightnessDown exec brightnessctl -q -e set 5%- && ( perl -e "use Math::Complex; printf \"%.0f\n\", 100 * ((`brightnessctl get` / `brightnessctl m`)**0.25)" > $SWAYSOCK.wob )
```suggestion
bindsym XF86MonBrightnessDown exec brightnessctl -q -e set 5%- && ( perl -e 'use Math::Complex; printf \"%.0f\n\", 100 * ((`brightnessctl get` / `brightnessctl m`)**0.25)' > $SWAYSOCK.wob )
```

2023-05-22 09:58 UTC, denisok commented on .config/sway/config.d/50-openSUSE.conf
> +bindsym XF86MonBrightnessUp exec brightnessctl -q -e set +5% && ( perl -e "use Math::Complex; printf \"%.0f\n\", 100 * ((`brightnessctl get` / `brightnessctl m`)**0.25)" > $SWAYSOCK.wob )
```suggestion
bindsym XF86MonBrightnessUp exec brightnessctl -q -e set +5% && ( perl -e 'use Math::Complex; printf \"%.0f\n\", 100 * ((`brightnessctl get` / `brightnessctl m`)**0.25)' > $SWAYSOCK.wob )
```

2024-01-17 10:03 UTC, denisok commented
@nova-r could you please check suggestions?

2024-01-23 11:10 UTC, denisok commented
@FilippoBonazziSUSE could you please check this one. When I checked it last time, it didn't work for me.

2024-01-25 09:29 UTC, FilippoBonazziSUSE requested changes
The commands work for me (with the necessary `'` to `"` fix) in the sense that they succeed in changing brightness.

However, there are 3 things that I would like to see changed:

1. The use of the Perl interpreter is not ideal, and I'd like to avoid it if at all possible. Any extra dependency must be carefully considered
2. The brightness up and down commands are not symmetrical, i.e. increments on the way up are different from decrements on the way down. This makes brightness values not reproducible and arbitrary looking. For example, starting from 20%, going up to 100% takes N increments, but going back down N decrements arrives at 19%. This needs to be fixed before this can be merged.
3. There is no progress on the discussion we had in #112 , and I'd like to see those points addressed too

2024-01-25 09:30 UTC, FilippoBonazziSUSE commented
@denisok This feature will take a bit more time, let's not wait for this for 0.16.0

2024-01-30 23:34 UTC, mcepl requested changes

2024-01-30 23:34 UTC, mcepl commented on .config/sway/config.d/50-openSUSE.conf
> +bindsym XF86MonBrightnessDown exec brightnessctl -q -e set 5%- && ( perl -e "use Math::Complex; printf \"%.0f\n\", 100 * ((`brightnessctl get` / `brightnessctl m`)**0.25)" > $SWAYSOCK.wob )
Pulling in yet another programming language (Perl) is not a good idea. Look at https://github.com/openSUSE/openSUSEway/issues/126 as well.

2024-08-22 15:01 UTC, closed without merging