Add openSUSE wob theme
openSUSE/openSUSEway pull request #68
Opened 2022-07-05 23:15 UTC by FilippoBonazziSUSE

Add theme using wob command line options. Closes #47.

Upstream wob has moved to a .ini configuration file, but has not released the next version yet.
It will be easy to migrate this configuration to the wob.ini format once it is released.

2022-07-06 06:33 UTC, jubalh requested changes
I would suggest to squash the 2 commits into 1

2022-07-06 07:13 UTC, FilippoBonazziSUSE commented
Was this the right way to do it?

2022-07-06 07:40 UTC, jubalh approved these changes
Didn't check the look though

2022-07-10 09:15 UTC, denisok approved these changes

2022-07-10 09:15 UTC, merged

2022-07-10 09:15 UTC, denisok commented
@FilippoBonazziSUSE thanks for contributing!